### ISSUE TITLE
Should it work with Python3

### ISSUE THREAD

**Issue by ivan133** [kiorky/spynner#103]
When I try to run examples for example

python google.py 

I got 

```
Traceback (most recent call last):
  File "/home/ivan133/.local/lib/python3.6/site-packages/spynner/browser.py", line 1680, in createRequest
    jar.allCookies(),
  File "/home/ivan133/.local/lib/python3.6/site-packages/spynner/browser.py", line 1587, in merge_cookies
    k = kf % get_cookie_info(i)
  File "/home/ivan133/.local/lib/python3.6/site-packages/spynner/browser.py", line 1567, in get_cookie_info
    domain_flag = str(cookie.domain().toUtf8()).startswith(".")
AttributeError: 'str' object has no attribute 'toUtf8'
[1]    11953 segmentation fault (core dumped)  python3 google.py
```

**Comment by kiorky** [comment]
python3 wont be supported.
