### ISSUE TITLE
No longer working under Ubuntu, Yakkety 16.10+

### ISSUE THREAD

**Issue by mixmastamyk** [kiorky/spynner#97]
Hi,

Can no longer run spynner on Ubuntu Yakkety 16.10, looks like QtWebKit  was removed:

```
  import spynner
  File "build/bdist.linux-x86_64/egg/spynner/__init__.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/spynner/browser.py", line 59, in <module>
ImportError: No module named QtWebKit
```

http://askubuntu.com/questions/840318/importerror-no-module-named-pyqt4-qtwebkit

QT5.Webkit looks to be available still.

I found: python-pyside.qtwebkit but not sure if it will work.

**Comment by ivan133** [comment]
I have the same issue on python 2
I've insttalled sudo apt-get install python-pyside 
But now it's different error

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spynner/browser.py", line 1683, in createRequest
    url = six.u(toString(request.url()))
  File "/home/ivan133/.local/lib/python2.7/site-packages/six.py", line 647, in u
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
TypeError: decoding Unicode is not supported

```

**Comment by kiorky** [comment]
Spynner is not maintained for years, but of course you can submit PR that i ll review and merge.
I can also submit new releases, but i have not the time right know to do more maintaining stuff.
